Repository Intro-to-SE-lab-Spring-22/Group-8, pull requests merged in 2022-04, with the labels that each got.

#45 Posts
  docs/class/database/post.md
  docs/class/database/user.md
  docs/class/post.md
  docs/database-setup.md
  public/action/post.php
  src/Database.php
  src/Database/Post.php
  src/Database/User.php
  src/Post.php
Labels: enhancement, glhf

#59 Beginning of Friends
  docs/Friends.md
  docs/class/FriendHandler.md
  docs/class/PostHandler.md
  docs/class/database/friend.md
  docs/database-setup.md
  public/action/friend.php
  public/action/post.php
  src/.gitkeep
  src/Auth.php
  src/Database/Friends.php
  src/Database/Post.php
  src/FriendHandler.php
  src/PostHandler.php
  src/Render.php
Labels: enhancement, glhf

#65 True Login, Auth, /action/ docs, and Javascript stuff
  docs/action/Friend.md
  docs/action/Login.md
  docs/action/Logout.md
  docs/action/Post.md
  docs/action/Register.md
  docs/action/Username.md
  docs/class/Auth.md
  public/UserPage.php
  public/action/friend.php
  public/action/login.php
  public/action/logout.php
  public/action/post.php
  public/action/register.php
  public/action/username.php
  src/Auth.php
  src/LogVer.php
  src/PostHandler.php
Labels: bug, enhancement, glhf

#68 Userpage Update and About page addition
  public/About.php
  public/UserPage.php
  public/assets/css/About.css
  public/assets/img/icon-ios7-gear-512.webp
  public/assets/js/UserPage.js
Labels: enhancement

#69 New user functions
  docs/class/database/user.md
  docs/database-setup.md
  src/Database/User.php
Labels: enhancement
